const contractAddress = "0xb5a49eb6777da73a62fde7a5afd99c5e9f3cd546"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "CryptoSpeechLess!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'CryptoSpeechLess is a collection of 1,000 unique auto-generated NFTs. SpeechLess, are a race of very advance species. They have been around since thousands of millennia. They truly have seen the universe and witnessed things, beyond the capabilities of our imagination and our ability to grasp. That may be the very reason they evolved to lose their voice. Words to communicate and a voice to be heard, they can create as well as destroy, they can bring peace and prosperity or wage war. SpeechLess, chose to be quiet. Silence, is not powerlessness and they are certainly not weak. Now, they watch over the universe, spread far and wide. Watching everything, silently.';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. 😢 Please try again.";